/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fridgeproject;

import java.applet.AppletContext;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.MalformedURLException;
import java.net.URL;
import javax.swing.JButton;

/**
 *
 * @author Pengwei Lan <pul139 at psu.edu>
 */
public class Fridge extends javax.swing.JApplet implements ActionListener {

    /**
     * Initializes the applet Fridge
     */
      PeopleList addressBook = new PeopleList();
      PeopleList searched = new PeopleList();
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fridge.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the applet */
       
        initComponents();
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jButton3.addActionListener(this);
        jButton4.addActionListener(this);
        jButton5.addActionListener(this);
        jButton6.addActionListener(this);
        jButton7.addActionListener(this);
        jButton8.addActionListener(this);
        jButton9.addActionListener(this);
        jButton10.addActionListener(this);
        jButton11.addActionListener(this);
        jButton12.addActionListener(this);
         
        jButton13.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) 
    {
        String name = jTextField1.getText();
        String number = jTextField2.getText();
        String age = jTextField3.getText();
        String twitterHandle = jTextField4.getText();
        People newPerson = new People(name,number,age,twitterHandle);
        addressBook.addPerson(newPerson);
        jTextArea1.setText(name + " has been added to the book.");
    }
  }
);
           jButton14.addActionListener(new ActionListener() {
    @Override
    public void actionPerformed(ActionEvent e) 
    {
        if(jTextField5.getText().matches(""))
                   {
                       searched = addressBook.searchNumber(jTextField6.getText());
                   }
        else if(jTextField6.getText().matches(""))
                   {
                       searched = addressBook.searchName(jTextField5.getText());
                   }
        else
            searched = addressBook.searchBoth(jTextField5.getText(), jTextField6.getText());
        String text = "";
        for(int i = 0; i < searched.getSize(); i++)
                   {
                       People temp = searched.getPerson(i);
                       text = text + temp.outputPerson(temp) + "\r\n";
                   }  
        jTextArea1.setText(text);
    }
  }
);
                    
                    
           
    }
    
    
    @Override
    public void actionPerformed(ActionEvent e)           
    {
        // Code for processing user actions
    	JButton source = (JButton)e.getSource();
        String link = "http://"+source.getText()+".com";
        try {
           AppletContext a = getAppletContext();
           URL url = new URL(link);
           a.showDocument(url,"_self");
        }
        catch (MalformedURLException eURL){
           System.out.println(eURL.getMessage());
        }
    	
        repaint();                                       
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton13 = new javax.swing.JButton();
        jTextField6 = new javax.swing.JTextField();
        jButton14 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jButton1.setText("facebook");
        jPanel1.add(jButton1);
        jButton1.setBounds(110, 120, 200, 90);

        jButton2.setText("twitter");
        jPanel1.add(jButton2);
        jButton2.setBounds(380, 120, 200, 90);

        jButton3.setText("instagram");
        jPanel1.add(jButton3);
        jButton3.setBounds(110, 250, 200, 90);

        jButton4.setText("pinterest");
        jPanel1.add(jButton4);
        jButton4.setBounds(380, 250, 200, 90);

        jTabbedPane1.addTab("Social Media", jPanel1);

        jPanel2.setLayout(null);

        jButton5.setText("pandora");
        jPanel2.add(jButton5);
        jButton5.setBounds(110, 120, 200, 90);

        jButton6.setText("spotify");
        jPanel2.add(jButton6);
        jButton6.setBounds(380, 120, 200, 90);

        jButton7.setText("music.google");
        jPanel2.add(jButton7);
        jButton7.setBounds(110, 250, 200, 90);

        jButton8.setText("grooveshark");
        jPanel2.add(jButton8);
        jButton8.setBounds(380, 250, 200, 90);

        jTabbedPane1.addTab("Music", jPanel2);

        jPanel3.setLayout(null);

        jButton9.setText("pizzahut");
        jPanel3.add(jButton9);
        jButton9.setBounds(110, 120, 200, 90);

        jButton10.setText("dominos");
        jPanel3.add(jButton10);
        jButton10.setBounds(380, 120, 200, 90);

        jButton11.setText("papajohns");
        jPanel3.add(jButton11);
        jButton11.setBounds(110, 250, 200, 90);

        jButton12.setText("mcdonalds");
        jPanel3.add(jButton12);
        jButton12.setBounds(380, 250, 200, 90);

        jTabbedPane1.addTab("Food", jPanel3);

        jPanel4.setLayout(null);

        jLabel1.setText("Enter your information:");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(80, 20, 190, 30);

        jLabel2.setText("Name:");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(80, 90, 40, 16);
        jPanel4.add(jTextField1);
        jTextField1.setBounds(160, 80, 160, 40);

        jLabel3.setText("Number:");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(70, 150, 60, 16);
        jPanel4.add(jTextField2);
        jTextField2.setBounds(160, 140, 160, 40);

        jLabel4.setText("Age:");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(90, 210, 28, 16);
        jPanel4.add(jTextField3);
        jTextField3.setBounds(160, 200, 160, 40);

        jLabel5.setText("Twitter Handle:");
        jPanel4.add(jLabel5);
        jLabel5.setBounds(25, 270, 100, 16);

        jLabel6.setText("Search by:");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(430, 20, 70, 16);

        jLabel7.setText("Name:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(430, 80, 40, 16);
        jPanel4.add(jTextField4);
        jTextField4.setBounds(160, 260, 160, 40);

        jLabel8.setText("-or-");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(490, 140, 29, 16);

        jLabel9.setText("Number:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(420, 200, 60, 16);
        jPanel4.add(jTextField5);
        jTextField5.setBounds(520, 70, 160, 40);

        jButton13.setText("Add");
        jPanel4.add(jButton13);
        jButton13.setBounds(160, 320, 75, 29);
        jPanel4.add(jTextField6);
        jTextField6.setBounds(520, 190, 160, 40);

        jButton14.setText("Search");
        jPanel4.add(jButton14);
        jButton14.setBounds(520, 270, 85, 29);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel4.add(jScrollPane1);
        jScrollPane1.setBounds(64, 400, 600, 130);

        jTabbedPane1.addTab("Contact", jPanel4);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(1, 1, 730, 600);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration//GEN-END:variables
}
